scripts/Themes/play.py
=> fix(themes/play.py): EOL

scripts/User_Management/refresh_user.py, scripts/_utils/makehomedirs.sh
- Closes #41
- Adds more verbose steps
- Added a new recovery phase, if the operations failed it will try to create a new home_dir one last time before exiting.
- [#L59](https://github.com/punctuations/hackerspace-scripts-2/blame/8387f1c07f3f640b664f5a7a7b8cd9ff60a07eab/scripts/User_Management/refresh_user.py#L59)
- Added makehomedirs.sh, with an informational message at the top.
=> Fix #41; Amendments to refresh_user

requirements.txt, scripts/Projector/flex_schedule_off.py, scripts/Projector/flex_schedule_on.py, scripts/Projector/set_flex_schedule.py
Added:
- new command set_flex_schedule 
- This command will change the current schedule that runs on flex days
- Added new dependency to requirements
Fixes:
- Fixed flex_schedule_off and flex_schedule_on
- Change the path to toggle scripts
=> feat(projector): add flex toggling

scripts/User_Management/refresh_user.py, scripts/User_Management/repair_user_desktop.py
=> fix(user_management): fix getpass

scripts/_utils/utils.py
Adds fix for #48 
Issue was `Image.open(file_url)`
=> fix(verify_image): fix non-local files

scripts/_utils/utils.py
=> feat(utils/image_verify): svg -> png

Dockerfile, README.md
Additions:
- Add Dockerfile
- Update docs with how-to
Issues:
- Closes #68
=> feat(docker): add Dockerfile

scripts/TVs/add_new_title.py
=> fix(TVs/add_title): returns gracefully

scripts/_utils/utils.py
added remove_transparency func to utils, used in image_verify.
Closes #64
=> feat(utils/remove_transparency): remove transparency of pngs

requirements.txt, scripts/TVs/add_new_collection.py, scripts/TVs/add_to_collection.py
ADDITIONS:
- add_new_collection
- add_to_collection
CHANGES:
- updated inquirer 2.7.0 => 2.10.0
ISSUES:
- closes #67
- closes #66
=> feat(collections): add collections scripts

scripts/_utils/utils.py
=> fix(verify_image): remove transparency on svgs

scripts/TVs/add_new_media.py
FIXES:
- Does not fail when everything is None
- will restart loop if TV # is none
- return "q" as output from get_media_url to actually quit instead of throwing error
ISSUES:
- closes #65
=> fix(add_new_media): dont fail on no username

scripts/TVs/add_new_collection.py, scripts/TVs/add_new_media_to_collection.py
=> fix(collections): address comments

Dockerfile, scripts/Workstation_Management/empty_shared_dir.py, scripts/Workstation_Management/empty_shared_drive.py
closes [#3](https://github.com/timberline-secondary/hackerspace-control-repo/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) in hackerspace-control-panel
=> feat(empty_shared): add empty_shared_drive command

scripts/Miscellaneous/toggle_grade_9_mode.py
FIXES:
- added outputting of what doing (i.e. "Muting entrance theme machine...")
- Only toggling power of TVs 1-3
ISSUES:
- closes #80
=> fix(grade_9): only toggle power of 1-3

scripts/Workstation_Management/empty_shared_dir.py
=> feat: empty by user

scripts/Workstation_Management/run_command_on_computers.py
ADDITIONS:
- Adds new run_command_on_computers command
ISSUES:
- closes #87
=> feat(run_all): add run command all computers command

requirements.txt, scripts/Workstation_Management/empty_shared_dir.py
ADDITIONS:
- added file sizes of folders
- added humanize requirements (turns bytes to human readable byte-scale [mB, kB, TB, etc.])
ISSUES:
- closes #85
=> feat(shared_script): add folder size of shared file

scripts/Workstation_Management/lab_report.py, scripts/Workstation_Management/run_command_on_computers.py
=> feat(lab_report): add lab report command

scripts/Workstation_Management/lab_report.py, scripts/Workstation_Management/run_command_on_computers.py
=> fix(lab_report): crash + space

scripts/Workstation_Management/_remove_puppet_lock.py, scripts/Workstation_Management/puppet_clear_certificates.py, scripts/_utils/utils.py
CHANGES:
- Allowing for space-seperated computer numbers (like most other commands)
ISSUES:
- closes #93
=> refactor(puppet_cert): refactor puppet cert command

scripts/TVs/collection_add_media.py, scripts/TVs/collection_create_new.py
ISSUES:
- closes #100
BREAKING CHANGES:
- add_new_media_to_collection  -> collection_add_media
- add_new_collection -> collection_create_new
=> chore(collections): rename commands

scripts/TVs/_utils.py, scripts/TVs/add_new_media.py, scripts/_utils/utils.py
CHANGES:
- Fixes the verify_mimetype to allow for gif entry
- tweak output of verify_media_integriddy to allow for conversions between file types to work
ISSUES:
- closes #99
=> fix(tv/gif): allow gif processing in add_new_media.py

scripts/Workstation_Management/puppet_clear_certificates.py
emergency fix of puppet clear cert
=> fix!(puppet): remove computer validation

scripts/Workstation_Management/puppet_clear_certificates.py
fixes the issue with computer hostnames in puppet_clear_certs
=> fix(puppet): fix compiuter hostname issue

scripts/TVs/remove_media.py
CHANGES:
- [remove_media]: added refresh_video to the script instead of just a warning to do so.
ISSUES:
- closes #103
=> fix(remove_media): add refresh of slideshow after removing media

scripts/Workstation_Management/empty_shared_dir.py, scripts/Workstation_Management/lab_report.py, scripts/Workstation_Management/run_command_on_computers.py
=> chore(method): update to use compartmentalized method

scripts/TVs/add_new_media.py, scripts/_utils/utils.py
CHANGES:
- updated the verify_image_integrity function is `_utils/utils.py`
- Added valid_types to allow only images to prevent pillow errors on videos
- updated add_new_media command
- added missing line in 'add another image'
ISSUES:
- closes #112 
- closes #111
=> fix(add_new_media): fix video file rejection

scripts/TVs/add_new_media.py
revert to functionality to how it was (per https://github.com/timberline-secondary/hackerspace-scripts-2/pull/113#issuecomment-1327874667)
=> revert(add_new_media): revert to how it was

scripts/TVs/add_new_media.py
=> fix(collection_new_media): media_url

scripts/TVs/remove_media.py, scripts/TVs/view_or_remove_media.py
=> fix(remove_media): add preview for all media

scripts/_utils/utils.py
CHANGES:
- Fixes the length of gifs issue, if a gif duration is <5s then it will loop until it reaches >=5s
ISSUES:
- closes #115
=> fix(gif): fix length of gifs

scripts/TVs/view_or_remove_media.py
=> fix(remove_media): formatting & no videos

scripts/_utils/utils.py
=> chore(process_gif): add feedback

scripts/TVs/add_new_media.py
CHANGES:
- changes the refresh users prompt to be at the end of the process
- it will append student usernames to a list and iterate through all to refresh them at the end
ISSUES:
- fixes #111
=> fix(add_new_media): append and refresh all at end

scripts/TVs/view_or_remove_media.py
CHANGES:
- Changed the Inquirer choices param to use `dir_contents` not `dir_contents.append(<...>)`
ISSUES:
- fixes #127
=> fix(rm_media): change choices to not be a method

scripts/_utils/utils.py
CHANGES:
- fixed 'all' keyword for get_computers_prompt
ISSUES:
- fixes #136
=> fix(get_computes_prompt): fix all

requirements.txt, scripts/_utils/utils.py
CHANGES:
- use imageio for gif conversion as it produces better results
ISSUES:
- fixes #128
=> fix(process_gif): fix short gif conversion

scripts/_utils/utils.py
+ frames -> generator (frames will empty after one use of generator)
issues:
- should close #132 
I lied I was not done
=> fix(process_gif): remove transparency

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
(added to make it easier and faster to submit them)
=> feat(template): created a pull request template

scripts/_utils/utils.py
=> fix(gif->mp4)?: specify h264 codec

scripts/TVs/add_new_media.py, scripts/_utils/utils.py
Solve the gif issue (once and for all) using ffmpeg conversion to ensure correct codecs and sizing and whatnot, a previous push implemented this but this a patch to that, finally solving it. This was tested on a pc with lab qualities (Ubuntu 20.04.5 not in docker).
TECHNICAL CHANGES:
- Changed ffmpeg command to use -y flag (yes flag) as before it was awaiting input.
- ffmpeg will log to stderr on return 1 (minor error), that is why stderr cannot be used for this.
- fixed add_new_media if not success to match the signature of 4 values to unpack.
RELATED ISSUES:
- Fixes #141 (tested on ubuntu pc in lab)
=> fix: ffmpeg conversion

scripts/_utils/utils.py
Fix png transparency, in this it will also now basically just remove alpha channel and keep whatever colour was supposed to be there (just without transparency)
TECHNICAL CHANGES:
- removed masking
- Changed to use PIL built-in `.convert('RGB')`
RELATED ISSUES:
- Fixes #146 (tested on a lab pc)
=> fix: png transparency

.github/workflows/main.yml, scripts/User_Management/reset_password.py, scripts/_utils/utils.py
SSH connection was erroring out as the connection would not be established due to an incorrect password and then the program would call an undefined variable, thus causing the issue. This PR will add a check to ensure a connection is established successfully, else it will return gracefully
TECHNICAL CHANGES:
- Added statement to check if ssh_connection is established
RELATED ISSUES:
- Closes #155
=> fix: bad password

requirements.txt, scripts/TVs/turn_tv_pi_off_and_on_again.py, scripts/TVs/tv_report.py
Added TV report command to see if a TV pi has crashed due to bad media
TECHNICAL CHANGES:
- Added new command
- Updated requirements to include new dependency
- Added parameter to turn_tv_pis_on_and_off_again to automate the process and call the method from new command
RELATED ISSUES:
- Closes #158 
**Flowchart:**
_Note: the reboot of TV pi is omitted from the flowchart but it would take place at the end of refreshing slideshow (top row)_
=> feat: TV_report command
